//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liczniki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licznik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Licznik()
        {
            this.Odczyt = new HashSet<Odczyt>();
            this.Wplata = new HashSet<Wplata>();
        }
    
        public int Id { get; set; }
        public string NrLicznika { get; set; }
        public Nullable<decimal> StanPoczatkowy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odczyt> Odczyt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wplata> Wplata { get; set; }
    }
}
